version: '3.8'

services:
  frontend:
    build:
      context: ./Front
    ports:
      - "3000:3000"
    container_name: frontend-container
    env_file:
      - /home/importent/.env
    networks:
      - lunch-network

  backend:
    build:
      context: ./Back
    ports:
      - "3001:8080"
    container_name: backend-container
    env_file:
      - /home/importent/.env
    volumes:
      - /home/importent:/home/importent
      - /var/www/uploads:/var/www/uploads
    networks:
      - lunch-network

networks:
  lunch-network:
    external: true