# Node 설정
FROM node:20

# 작업 폴더 설정
WORKDIR /app

# 의존성 읽어오기
COPY package.json package-lock.json ./

# 의존성 설치
RUN npm install
COPY . .

# 애플리케이션 포트 설정 (8080 포트 사용)
EXPOSE 8080

# 애플리케이션 실행
CMD ["node", "app.js"]
