import Head from 'next/head';
import React from 'react';

export const metadata = {
  title: '오늘의 우렁각시 메뉴는?',
  description: 'Generated by chanbeen',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        {/* Google Analytics script */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GKEY}"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GKEY}');
            `,
          }}
        />
      </Head>
      <body>{children}</body>
    </html>
  );
}