export const metadata = {
  title: '오늘의 우렁각시 메뉴는?',
  description: 'Generated by chanbeen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
