name: Azure Static Web CI/CD (FRONT)

on:
  push:
    branches:
      - main
    paths:
      - 'Front/**'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: 🪛 Frontend 빌드 및 배포 작업

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: ☕ 빌드 및 배포
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Front"

          api_location: ""
          output_location: ""
        env:
          NEXT_PUBLIC_GKEY: ${{ secrets.NEXT_PUBLIC_GKEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}